### ISSUE TITLE
Guides Links are not opening. https://github.com/hashicorp/consul-guides#guides

### ISSUE THREAD

**Issue by kodi1981** [hashicorp/consul-guides#7]
Guides . 
Provision a Dev Consul Cluster locally with Vagrant
Provision a Dev Consul Cluster on AWS with Terraform
Provision a Quick Start Consul Cluster on AWS with Terraform
Provision a Best Practices Consul Cluster on AWS with Terraform

**Comment by bensojona** [comment]
This should be resolved
